version: 2.0.6

orbs:
  node: circleci/node@4.5.0

jobs:
  publish-package:
    docker:
      - image: 'cimg/base:2020.01'
    steps:
      - attach_workspace:
          at: .
      - checkout
      - node/install:
          node-version: '10.24.1'
      - run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run: npm install
      - run: npm version from-git --no-git-tag-version 
      - run: npm publish

workflows:
  version: 2
  build-publish:
    jobs:
      - publish-package:
          context: wp-backbone-deep-model
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/